### ISSUE TITLE
`chunksize` parameter missing from `CatalogueConstructor.set_preprocessor_params()`

### ISSUE THREAD

**Issue by subhacom** [tridesclous/tridesclous#129]
In the current version 1.3.2-dev0 (installed from github master) the `chunksize` parameter exists in docs and example, but missing from the actual code, resulting in exception in user code with `chunksize` specified.
Edit: specifically `example_locust_dataset.py` in the `example` folder and the documentation [here](https://tridesclous.readthedocs.io/en/latest/parameters.html) seems to be out of sync with the current  code.

**Comment by samuelgarcia** [comment]
Thank you for catching this.
I forgot to change the API in examples except in ipynb.


Now there are 2 ways see : example_olfactory_bulb_dataset.ipynb or example_locust_dataset.ipynb

Manual way, note that now there are 3 methods (one before). 
```python
# global params
catalogueconstructor.set_global_params(chunksize=1024,mode='dense')
# pre processing filetring normalisation
catalogueconstructor.set_preprocessor_params(
            common_ref_removal=False,
            highpass_freq=300.,
            lowpass_freq=5000.,                                             
            lostfront_chunksize=64)
# peak detector
catalogueconstructor.set_peak_detector_params(
            peak_sign='-',
            relative_threshold=6.5,
            peak_span_ms=0.1)
```

Or totally automatic.
```python
params = tdc.get_auto_params_for_catalogue(dataio, chan_grp=0)
pprint(params)
tdc.apply_all_catalogue_steps(catalogueconstructor, params, verbose=True)
```


In your case the missing chanksize is due to the lake of **set_global_params**

**Comment by samuelgarcia** [comment]
Se #131.
