### ISSUE TITLE
Docs: mention that DataIO RawData expects channels as columns

### ISSUE THREAD

**Issue by subhacom** [tridesclous/tridesclous#133]
It will probably make life easier for users with custom data formats: the API docs for `DataIO` should mention that when reading `RawData`, the saved array is read as if the channels were in columns and time points in rows.

**Comment by samuelgarcia** [comment]
thank you for this deep inspection.


It was by design.
Normally a user should always do 
```dataio.set_probe_file()```

but for new user that don't want to fight with this prb file. I decide to make an automatic fake (and bad) probe. Linear for N>4 and a circle for a tetrode.

I thought it could help new user to discover without to deal with the geomtry to do a quick start.

Feel free to enhance the doc on **important_details** page.
