### ISSUE TITLE
Crashes on refining cluster catalogue

### ISSUE THREAD

**Issue by vncntprvst** [tridesclous/tridesclous#34]
I've been playing around with the GUI, using the data I shared earlier. 
It works pretty well.  
![image](https://user-images.githubusercontent.com/1872756/32683367-b95f4a86-c648-11e7-93ef-0a2b9d0ea21f.png)

Once the data is processed, however, some actions can trigger crashes, especially when trying to refine clusters with the functions available on the right hand side. 
Here's one error output example among a few: 
`construct_catalogue 6.538290827028732
Traceback (most recent call last):
  File "C:\Anaconda\envs\tridesclous\lib\site-packages\tridesclous-0.2.0.dev0-py
3.6.egg\tridesclous\gui\cataloguewindow.py", line 166, in save_catalogue
  File "C:\Anaconda\envs\tridesclous\lib\site-packages\tridesclous-0.2.0.dev0-py
3.6.egg\tridesclous\catalogueconstructor.py", line 1001, in save_catalogue
  File "C:\Anaconda\envs\tridesclous\lib\site-packages\tridesclous-0.2.0.dev0-py
3.6.egg\tridesclous\dataio.py", line 336, in save_catalogue
  File "C:\Anaconda\envs\tridesclous\lib\site-packages\tridesclous-0.2.0.dev0-py
3.6.egg\tridesclous\iotools.py", line 89, in add_array
  File "C:\Anaconda\envs\tridesclous\lib\site-packages\tridesclous-0.2.0.dev0-py
3.6.egg\tridesclous\iotools.py", line 79, in create_array
  File "C:\Anaconda\envs\tridesclous\lib\site-packages\numpy\core\memmap.py", li
ne 221, in __new__
    fid = open(filename, (mode == 'c' and 'r' or mode)+'b')
OSError: [Errno 22] Invalid argument: 'C:/Data/raw/Blackrock/039v_1011\\tdc_039v
_1011_WheelRunning_LaserStim\\channel_group_0\\catalogues\\initial\\cluster_labe
ls.raw'`

**Comment by samuelgarcia** [comment]
Nice.

I known for theses crashes in CatalogueWindow. Since I try to make UI flexible (re detect peak, re prject, re cluster, ...) the dataflow is a bit complicated and the internal state is sometimes not unanticipated. This causes crashes in Qt5 on  callbacks. I could make them silent but I prefer for the moment a clear crash with a clear message so I get feedback.

Getting capy/paste from trhe console after a crash help a lot. Thank you. Even if here, I don' anderstand...

The crash orrdured on 'save_catalogue', right ? Was it the first or the second time you push 'save_catatlogue' ?

**Comment by vncntprvst** [comment]
I think it was the second time I saved the catalogue. Not exactly sure. I'll post again if/when that issue comes back.

**Comment by samuelgarcia** [comment]
Thank you for this.

This should be fixed by #46.
