### ISSUE TITLE
directly read spike waveform snippets and skip preprocessing?

### ISSUE THREAD

**Issue by fkloosterman** [tridesclous/tridesclous#63]
I am checking out tridesclous and it looks interesting so far. I noticed that Neuralynx' .ncs files are supported, but we also have many recordings in which have only the waveform snippets in .ntt files. Is there a way to bypass some of the preprocessing in tridesclous and directly use these pre-detected spikes?

Thanks,
Fabian

**Comment by samuelgarcia** [comment]
Dear Fabian,
unfortunately tdc do not deal with spike waveforms.
I am sorry.

TDC used only full band recording by design and by choice.

Not recording the raw signal trace is quite a bad pratice because:

  * the threshold cannot be changed after.
  * The filter cannot be changed (even worst)
  * on-line device make a very poor waveform alignment (very crucial step!!)
  * Multi channel spike detection online is quite bad in general
  * read the data snippet are super slow
  * you cannot resolve spike waveform superposition!!
  * in some situation the file size of snippet (with low threshold) can be bigger that the signal itself!!
  * With spike waveforms you can only do the CatalogueWindow step.

I would strongly recommend to record the full trace with no filter at all.

With old data that do NOT have the full band recording signal. There are 2 possible hacks:
  * explore the CatalogueConstructor class code and construct a fake one to be able to use
    the CatalogueWIndow with it. In short you must manually construct some attributes
    *all_peaks*, *some_waveforms*, ...
  * make a fake signal with zeros and paste the waveforms at the good place to mimic
   a a full band signal. In that case you must use no filtering and take a smaller waveforms width.



best

Samuel
