### ISSUE TITLE
Large number of unclassified spikes

### ISSUE THREAD

**Issue by julienfiorilli** [tridesclous/tridesclous#67]
Hi all,

I have been testing tridesclous with tetrode data from freely moving rats, and it has worked well for me so far. 
However, data from one tetrode is giving me issues. It seems to be a tetrode with a very high amount of spikes: These spikes are being detected but most of those spikes are not being classified in a cluster ( label: unclassified), while they are clearly good spikes.

I can not display the cloud of points associated to the unclassified cluster (maybe due to high number of n?) , and when I try to split/classify the unclassified cluster tdc crashes. This is intriguing as tdc has worked fine for other tetrodes with the same parameters. What could the reason be?

![clusters_unclassified](https://user-images.githubusercontent.com/38493997/41529494-a4f1644c-72ed-11e8-99fa-c39feed0a910.png)

**Comment by samuelgarcia** [comment]
You are in the CatalogueWindow.
This window is the first step : construct a catalogue. It is not teh final result at all.
The main goal is to have a robust catalogue of template.
In that step : all spikes are not taken in account because it is too big in memory.
The (-10) unclassifier label means 2 things : not classified or not not taken in account.

You have them to run the "Peeler" (template matching) on the same dataset. In the PeelerWindow, unclassified label (-10) really mean that a peak is uclassified. After peeler step unclassfied mean only one thing:: it do not match any waveform of the calatogue. And this can have 2 reasons : it noisy (too small) or the centroid was not in the catalogue.

A good way of using TDC is to:
  1. open CatalogueWindow
  3. do manual operation (split/merge/trash)
  4. Make catalogue for peeler
  5. run the peeler on the same duration
  6. Check the final result on PeelerWindow
  7. If not happy, go back to "2"

**Comment by julienfiorilli** [comment]
thanks for your explanation, I got confused by the fact that the label 'unclassified' means different things, dependent of whether you are in the Peeler window or in catalogue window. 

makes sense now

**Comment by samuelgarcia** [comment]
I plan add some label in the CatalogueWindow to avoid confusion (but it is not on the top 5 TODO list).

**Comment by MisterVulcan** [comment]
This is mostly academic because it's impractical, but if you change the `extract_waveforms=>mode` option from `rand` to `all` when initializing catalogue, it will classify all of the detected spikes instead of a randomly-sampled subset. Not recommended if you're not using multi-threading/opencl, and even then it's difficult to do any curation because catalogueviewer interface gets slowed down by the large datasets. I only think it's useful for doing a "trial" analysis on a single sequence, or possibly if you want to compare template sorting to normal cluster sorting.

**Comment by samuelgarcia** [comment]
mode='all' is also usefull when you make your catalogue on a short duration. If you have 12k peaks, it is not necessary to clip to 10k.

**Comment by MisterVulcan** [comment]
Oh, right; sorry. Me culpa.

**Comment by samuelgarcia** [comment]
The mea culpa is not necessary, it was just to say that:  the waveform sampling is more or less flexible and need to be adapeted for each case.

**Comment by samuelgarcia** [comment]
In my place here: https://github.com/samuelgarcia/tridesclous
I have a new label -11=NO_WAVEFORMS
You you are happy with this I can merge it.
This means that you will nedd to re run you catalogue.

**Comment by MisterVulcan** [comment]
I started looking at your personal branch, but I'm going to be away from my work computer for about a month so won't have time to test the modifications in detail until later. Ditto for the request superlist on main branch.

**Comment by samuelgarcia** [comment]
Close by #71
